//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppAssignment.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int orderID { get; set; }
        public int artworkID { get; set; }
        public Nullable<int> orderQuantity { get; set; }
    
        public virtual Artwork Artwork { get; set; }
        public virtual Order Order { get; set; }
    }
}
